name: Vote Snapshot

on:
  schedule:
    # Chạy mỗi 15 phút
    - cron: "*/15 * * * *"

  # Cho phép chạy thủ công
  workflow_dispatch:

jobs:
  update-snapshot:
    runs-on: ubuntu-latest

    steps:
      # Lấy source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Cài dependencies
      - name: Install dependencies
        run: npm install

      # Chạy job snapshot
      - name: Run snapshot
        run: npm run snapshot
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}